is_ubuntu: ansible_distribution == "Ubuntu"
is_osx: ansible_distribution == "MacOSX"

rbenv:
  dependencies:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev
