- apt: pkg=lxc
  when: is_ubuntu

- name: see if docker is installed
  shell: "[ -f /usr/bin/docker ] && echo 'Found' || echo ''"
  register: docker_installed
  when: is_ubuntu

- apt: pkg=software-properties-common state=latest update_cache=yes
  when: docker_installed is defined and not docker_installed.stdout

- apt_key: url=https://get.docker.io/gpg state=present
  when: docker_installed is defined and not docker_installed.stdout

- action: apt_repository repo='deb http://get.docker.io/ubuntu docker main' state=present update_cache=yes
  when: docker_installed is defined and not docker_installed.stdout

- name: install linux extras
  apt: pkg=linux-image-extra-virtual state=latest update_cache=yes

- name: install aufs tools
  apt: pkg=aufs-tools state=latest update_cache=yes

- apt: pkg=lxc-docker state=latest update_cache=yes
  when: docker_installed is defined and not docker_installed.stdout

- name: set docker path and aufs support
  lineinfile: dest=/etc/default/docker regexp="^DOCKER_OPTS=" line="DOCKER_OPTS=\"-g /mnt/docker -s aufs\""
  when: docker_installed is defined and not docker_installed.stdout

- name: restart docker
  service: name=docker state=restarted
  when: docker_installed is defined and not docker_installed.stdout

- name: add user to docker group
  user: name={{ user }} append=yes groups=docker
  when: is_ubuntu
